PATCH http://localhost:3001/edits/643897c240fa67706e5c8bf4
Content-Type: application/json

{
     "firstName":"Oh",

    "lastName":"Yea"
}

###
PATCH http://localhost:3001/edits/643897c240fa67706e5c8bf4
Content-Type: application/json

{
     "firstName":"Oh",

    "lastName":"Yea"
}